/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminApkFile {
  'uploadTimestamp' : bigint,
  'version' : string,
  'fileRef' : ExternalBlob,
}
export type AlertCategory = { 'warning' : null } |
  { 'educational' : null } |
  { 'contentBlock' : null };
export interface AlertMessageV2 {
  'id' : string,
  'alertType' : AlertType,
  'title' : string,
  'message' : string,
  'timestamp' : bigint,
  'category' : AlertCategory,
  'priority' : bigint,
}
export type AlertType = { 'violence' : null } |
  { 'inappropriateLanguage' : null } |
  { 'generalSafety' : null } |
  { 'explicitContent' : null };
export interface CardToken {
  'token' : string,
  'cardType' : string,
  'createdAt' : bigint,
  'last4' : string,
  'issuer' : string,
  'expiry' : string,
}
export interface ChildActivityStats {
  'blockedAttempts' : bigint,
  'lastActivity' : bigint,
  'totalTimeOnline' : bigint,
  'childId' : Principal,
  'safeSearchEnabled' : boolean,
  'parentId' : Principal,
}
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface CurrencyConversionRate {
  'toCurrency' : string,
  'fromCurrency' : string,
  'rate' : bigint,
  'lastUpdated' : bigint,
}
export type EncryptionStatus = { 'verified' : null } |
  { 'unverified' : null } |
  { 'failed' : null };
export type ExternalBlob = Uint8Array;
export interface FilterStatus {
  'lastUpdated' : bigint,
  'isActive' : boolean,
  'level' : string,
}
export interface HomeContent {
  'missionStatement' : string,
  'heroText' : string,
}
export interface NfcAlert {
  'id' : string,
  'alertType' : string,
  'user' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface NfcComplianceReport {
  'id' : string,
  'user' : Principal,
  'reportType' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface NfcDetectionLog {
  'id' : string,
  'detectedType' : NfcTransferType,
  'status' : string,
  'user' : Principal,
  'cardToken' : [] | [string],
  'timestamp' : bigint,
}
export interface NfcPermission {
  'phoneTransferConsent' : boolean,
  'user' : Principal,
  'lastUpdated' : bigint,
  'cardScanConsent' : boolean,
}
export interface NfcSettings {
  'cardScanEnabled' : boolean,
  'transactionLimit' : bigint,
  'user' : Principal,
  'lastUpdated' : bigint,
  'phoneTransferEnabled' : boolean,
  'defaultCurrency' : string,
}
export interface NfcTransaction {
  'id' : string,
  'to' : Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : Principal,
  'description' : string,
  'cardToken' : [] | [string],
  'currency' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type NfcTransactionStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type NfcTransferType = { 'phoneToPhone' : null } |
  { 'cardToPhone' : null };
export interface PaymentTransaction {
  'status' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export interface PdfGuide {
  'title' : string,
  'createdAt' : bigint,
  'navigation' : Array<string>,
  'sections' : Array<PdfSection>,
  'branding' : string,
}
export interface PdfSection {
  'title' : string,
  'content' : string,
  'images' : Array<string>,
}
export interface PortfolioProject {
  'id' : string,
  'title' : string,
  'imageRefs' : Array<ExternalBlob>,
  'description' : string,
  'details' : string,
}
export interface ReinforcementProgress {
  'positiveActions' : bigint,
  'childId' : Principal,
  'parentId' : Principal,
  'milestonesAchieved' : bigint,
  'lastReward' : bigint,
}
export interface SecurityAuditLog {
  'id' : string,
  'to' : Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : Principal,
  'description' : string,
  'verificationDetails' : string,
  'currency' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'encryptionStatus' : EncryptionStatus,
  'transactionId' : string,
}
export interface SecurityVerificationResult {
  'verificationDetails' : string,
  'timestamp' : bigint,
  'encryptionStatus' : EncryptionStatus,
  'transactionId' : string,
}
export interface Service {
  'title' : string,
  'features' : Array<string>,
  'description' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransactionReceipt {
  'to' : Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : Principal,
  'description' : string,
  'cardToken' : [] | [string],
  'currency' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletBalance {
  'balance' : bigint,
  'user' : Principal,
  'lastUpdated' : bigint,
  'currency' : string,
}
export interface WidgetConfig {
  'theme' : string,
  'refreshInterval' : bigint,
  'lastUpdated' : bigint,
  'widgetSize' : string,
  'parentId' : Principal,
}
export interface WidgetData {
  'filterStatus' : FilterStatus,
  'childStats' : Array<ChildActivityStats>,
  'lastAlert' : [] | [AlertMessageV2],
  'reinforcementProgress' : Array<ReinforcementProgress>,
  'timestamp' : bigint,
  'parentId' : Principal,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPortfolioProject' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, string],
    boolean
  >,
  'addService' : ActorMethod<[string, string, Array<string>], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPdfGuide' : ActorMethod<
    [string, Array<PdfSection>, string, Array<string>],
    string
  >,
  'deleteAdminApkFile' : ActorMethod<[], undefined>,
  'deletePdfGuide' : ActorMethod<[string], undefined>,
  'deletePortfolioProject' : ActorMethod<[string], boolean>,
  'deleteService' : ActorMethod<[string], boolean>,
  'generateWidgetAuthToken' : ActorMethod<[Principal, bigint], string>,
  'getAdminApkFile' : ActorMethod<[], [] | [AdminApkFile]>,
  'getAllPdfGuides' : ActorMethod<[], Array<PdfGuide>>,
  'getAllSecurityVerificationResults' : ActorMethod<
    [],
    Array<SecurityVerificationResult>
  >,
  'getCallerNfcPermission' : ActorMethod<[], [] | [NfcPermission]>,
  'getCallerNfcSettings' : ActorMethod<[], [] | [NfcSettings]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWalletBalance' : ActorMethod<[], [] | [WalletBalance]>,
  'getCallerWidgetData' : ActorMethod<[], [] | [WidgetData]>,
  'getCardToken' : ActorMethod<[string], [] | [CardToken]>,
  'getChildActivityStats' : ActorMethod<[Principal], [] | [ChildActivityStats]>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getCurrencyConversionRate' : ActorMethod<
    [string, string],
    [] | [CurrencyConversionRate]
  >,
  'getFilterStatus' : ActorMethod<[Principal], [] | [FilterStatus]>,
  'getHomeContent' : ActorMethod<[], [] | [HomeContent]>,
  'getNfcAlerts' : ActorMethod<[], Array<NfcAlert>>,
  'getNfcComplianceReports' : ActorMethod<[], Array<NfcComplianceReport>>,
  'getNfcDetectionLogs' : ActorMethod<[], Array<NfcDetectionLog>>,
  'getNfcPermission' : ActorMethod<[Principal], [] | [NfcPermission]>,
  'getNfcSettings' : ActorMethod<[Principal], [] | [NfcSettings]>,
  'getNfcTransactions' : ActorMethod<[], Array<NfcTransaction>>,
  'getPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getPdfGuide' : ActorMethod<[string], [] | [PdfGuide]>,
  'getPortfolioProjects' : ActorMethod<[], Array<PortfolioProject>>,
  'getReinforcementProgress' : ActorMethod<
    [Principal],
    [] | [ReinforcementProgress]
  >,
  'getSecurityAuditLogById' : ActorMethod<[string], [] | [SecurityAuditLog]>,
  'getSecurityAuditLogs' : ActorMethod<[], Array<SecurityAuditLog>>,
  'getSecurityAuditLogsByEncryptionStatus' : ActorMethod<
    [EncryptionStatus],
    Array<SecurityAuditLog>
  >,
  'getSecurityAuditLogsByTransactionId' : ActorMethod<
    [string],
    Array<SecurityAuditLog>
  >,
  'getSecurityAuditLogsByTransactionStatus' : ActorMethod<
    [NfcTransactionStatus],
    Array<SecurityAuditLog>
  >,
  'getSecurityAuditLogsByTransferType' : ActorMethod<
    [NfcTransferType],
    Array<SecurityAuditLog>
  >,
  'getSecurityAuditSummary' : ActorMethod<
    [],
    {
      'verifiedCount' : bigint,
      'failedCount' : bigint,
      'phoneToPhoneCount' : bigint,
      'totalLogs' : bigint,
      'completedCount' : bigint,
      'cardToPhoneCount' : bigint,
      'failedTransactionCount' : bigint,
      'unverifiedCount' : bigint,
    }
  >,
  'getSecurityVerificationResult' : ActorMethod<
    [string],
    [] | [SecurityVerificationResult]
  >,
  'getSecurityVerificationResultsByStatus' : ActorMethod<
    [EncryptionStatus],
    Array<SecurityVerificationResult>
  >,
  'getSecurityVerificationResultsByTimeRange' : ActorMethod<
    [bigint, bigint],
    Array<SecurityVerificationResult>
  >,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionReceipt' : ActorMethod<[string], [] | [TransactionReceipt]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitCount' : ActorMethod<[], bigint>,
  'getWalletBalance' : ActorMethod<[Principal], [] | [WalletBalance]>,
  'getWidgetConfig' : ActorMethod<[Principal], [] | [WidgetConfig]>,
  'getWidgetData' : ActorMethod<[Principal], [] | [WidgetData]>,
  'incrementVisitCount' : ActorMethod<[], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeDefaultPdfGuide' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordCardToken' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'recordChildActivityStats' : ActorMethod<
    [Principal, Principal, bigint, bigint, boolean, bigint],
    undefined
  >,
  'recordFilterStatus' : ActorMethod<[Principal, string, boolean], undefined>,
  'recordNfcAlert' : ActorMethod<[string, string], undefined>,
  'recordNfcComplianceReport' : ActorMethod<
    [string, string, Principal],
    undefined
  >,
  'recordNfcDetectionLog' : ActorMethod<
    [NfcTransferType, string, [] | [string]],
    undefined
  >,
  'recordNfcTransaction' : ActorMethod<
    [
      Principal,
      bigint,
      NfcTransferType,
      NfcTransactionStatus,
      [] | [string],
      string,
      string,
    ],
    string
  >,
  'recordPaymentTransaction' : ActorMethod<[bigint, string, string], undefined>,
  'recordReinforcementProgress' : ActorMethod<
    [Principal, Principal, bigint, bigint, bigint],
    undefined
  >,
  'recordSecurityAuditLog' : ActorMethod<
    [
      string,
      NfcTransactionStatus,
      EncryptionStatus,
      NfcTransferType,
      Principal,
      Principal,
      bigint,
      string,
      string,
      string,
    ],
    undefined
  >,
  'recordSecurityVerificationResult' : ActorMethod<
    [string, EncryptionStatus, string],
    undefined
  >,
  'recordTransactionReceipt' : ActorMethod<
    [
      string,
      Principal,
      bigint,
      string,
      NfcTransactionStatus,
      NfcTransferType,
      [] | [string],
      string,
    ],
    undefined
  >,
  'recordWidgetConfig' : ActorMethod<
    [Principal, string, string, bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerNfcPermission' : ActorMethod<[boolean, boolean], undefined>,
  'updateCallerNfcSettings' : ActorMethod<
    [string, bigint, boolean, boolean],
    undefined
  >,
  'updateContactInfo' : ActorMethod<[string, string, string], undefined>,
  'updateCurrencyConversionRate' : ActorMethod<
    [string, string, bigint],
    undefined
  >,
  'updateHomeContent' : ActorMethod<[string, string], undefined>,
  'updateNfcPermission' : ActorMethod<[Principal, boolean, boolean], undefined>,
  'updateNfcSettings' : ActorMethod<
    [Principal, string, bigint, boolean, boolean],
    undefined
  >,
  'updatePdfGuide' : ActorMethod<
    [string, Array<PdfSection>, string, Array<string>],
    undefined
  >,
  'updatePortfolioProject' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, string],
    boolean
  >,
  'updateService' : ActorMethod<[string, string, Array<string>], boolean>,
  'updateWalletBalance' : ActorMethod<[Principal, bigint, string], undefined>,
  'uploadAdminApkFile' : ActorMethod<[ExternalBlob, string], undefined>,
  'validateWidgetAuthToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];