/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PdfSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const AdminApkFile = IDL.Record({
  'uploadTimestamp' : IDL.Int,
  'version' : IDL.Text,
  'fileRef' : ExternalBlob,
});
export const PdfGuide = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'navigation' : IDL.Vec(IDL.Text),
  'sections' : IDL.Vec(PdfSection),
  'branding' : IDL.Text,
});
export const EncryptionStatus = IDL.Variant({
  'verified' : IDL.Null,
  'unverified' : IDL.Null,
  'failed' : IDL.Null,
});
export const SecurityVerificationResult = IDL.Record({
  'verificationDetails' : IDL.Text,
  'timestamp' : IDL.Int,
  'encryptionStatus' : EncryptionStatus,
  'transactionId' : IDL.Text,
});
export const NfcPermission = IDL.Record({
  'phoneTransferConsent' : IDL.Bool,
  'user' : IDL.Principal,
  'lastUpdated' : IDL.Int,
  'cardScanConsent' : IDL.Bool,
});
export const NfcSettings = IDL.Record({
  'cardScanEnabled' : IDL.Bool,
  'transactionLimit' : IDL.Nat,
  'user' : IDL.Principal,
  'lastUpdated' : IDL.Int,
  'phoneTransferEnabled' : IDL.Bool,
  'defaultCurrency' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WalletBalance = IDL.Record({
  'balance' : IDL.Nat,
  'user' : IDL.Principal,
  'lastUpdated' : IDL.Int,
  'currency' : IDL.Text,
});
export const FilterStatus = IDL.Record({
  'lastUpdated' : IDL.Int,
  'isActive' : IDL.Bool,
  'level' : IDL.Text,
});
export const ChildActivityStats = IDL.Record({
  'blockedAttempts' : IDL.Nat,
  'lastActivity' : IDL.Int,
  'totalTimeOnline' : IDL.Nat,
  'childId' : IDL.Principal,
  'safeSearchEnabled' : IDL.Bool,
  'parentId' : IDL.Principal,
});
export const AlertType = IDL.Variant({
  'violence' : IDL.Null,
  'inappropriateLanguage' : IDL.Null,
  'generalSafety' : IDL.Null,
  'explicitContent' : IDL.Null,
});
export const AlertCategory = IDL.Variant({
  'warning' : IDL.Null,
  'educational' : IDL.Null,
  'contentBlock' : IDL.Null,
});
export const AlertMessageV2 = IDL.Record({
  'id' : IDL.Text,
  'alertType' : AlertType,
  'title' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : AlertCategory,
  'priority' : IDL.Nat,
});
export const ReinforcementProgress = IDL.Record({
  'positiveActions' : IDL.Nat,
  'childId' : IDL.Principal,
  'parentId' : IDL.Principal,
  'milestonesAchieved' : IDL.Nat,
  'lastReward' : IDL.Int,
});
export const WidgetData = IDL.Record({
  'filterStatus' : FilterStatus,
  'childStats' : IDL.Vec(ChildActivityStats),
  'lastAlert' : IDL.Opt(AlertMessageV2),
  'reinforcementProgress' : IDL.Vec(ReinforcementProgress),
  'timestamp' : IDL.Int,
  'parentId' : IDL.Principal,
});
export const CardToken = IDL.Record({
  'token' : IDL.Text,
  'cardType' : IDL.Text,
  'createdAt' : IDL.Int,
  'last4' : IDL.Text,
  'issuer' : IDL.Text,
  'expiry' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CurrencyConversionRate = IDL.Record({
  'toCurrency' : IDL.Text,
  'fromCurrency' : IDL.Text,
  'rate' : IDL.Nat,
  'lastUpdated' : IDL.Int,
});
export const HomeContent = IDL.Record({
  'missionStatement' : IDL.Text,
  'heroText' : IDL.Text,
});
export const NfcAlert = IDL.Record({
  'id' : IDL.Text,
  'alertType' : IDL.Text,
  'user' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const NfcComplianceReport = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'reportType' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const NfcTransferType = IDL.Variant({
  'phoneToPhone' : IDL.Null,
  'cardToPhone' : IDL.Null,
});
export const NfcDetectionLog = IDL.Record({
  'id' : IDL.Text,
  'detectedType' : NfcTransferType,
  'status' : IDL.Text,
  'user' : IDL.Principal,
  'cardToken' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const NfcTransactionStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const NfcTransaction = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : IDL.Principal,
  'description' : IDL.Text,
  'cardToken' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const PaymentTransaction = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const PortfolioProject = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imageRefs' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'details' : IDL.Text,
});
export const SecurityAuditLog = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : IDL.Principal,
  'description' : IDL.Text,
  'verificationDetails' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'encryptionStatus' : EncryptionStatus,
  'transactionId' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TransactionReceipt = IDL.Record({
  'to' : IDL.Principal,
  'status' : NfcTransactionStatus,
  'transferType' : NfcTransferType,
  'from' : IDL.Principal,
  'description' : IDL.Text,
  'cardToken' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const WidgetConfig = IDL.Record({
  'theme' : IDL.Text,
  'refreshInterval' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'widgetSize' : IDL.Text,
  'parentId' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPortfolioProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPdfGuide' : IDL.Func(
      [IDL.Text, IDL.Vec(PdfSection), IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteAdminApkFile' : IDL.Func([], [], []),
  'deletePdfGuide' : IDL.Func([IDL.Text], [], []),
  'deletePortfolioProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateWidgetAuthToken' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getAdminApkFile' : IDL.Func([], [IDL.Opt(AdminApkFile)], ['query']),
  'getAllPdfGuides' : IDL.Func([], [IDL.Vec(PdfGuide)], ['query']),
  'getAllSecurityVerificationResults' : IDL.Func(
      [],
      [IDL.Vec(SecurityVerificationResult)],
      ['query'],
    ),
  'getCallerNfcPermission' : IDL.Func([], [IDL.Opt(NfcPermission)], ['query']),
  'getCallerNfcSettings' : IDL.Func([], [IDL.Opt(NfcSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWalletBalance' : IDL.Func([], [IDL.Opt(WalletBalance)], ['query']),
  'getCallerWidgetData' : IDL.Func([], [IDL.Opt(WidgetData)], ['query']),
  'getCardToken' : IDL.Func([IDL.Text], [IDL.Opt(CardToken)], ['query']),
  'getChildActivityStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ChildActivityStats)],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCurrencyConversionRate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CurrencyConversionRate)],
      ['query'],
    ),
  'getFilterStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FilterStatus)],
      ['query'],
    ),
  'getHomeContent' : IDL.Func([], [IDL.Opt(HomeContent)], ['query']),
  'getNfcAlerts' : IDL.Func([], [IDL.Vec(NfcAlert)], ['query']),
  'getNfcComplianceReports' : IDL.Func(
      [],
      [IDL.Vec(NfcComplianceReport)],
      ['query'],
    ),
  'getNfcDetectionLogs' : IDL.Func([], [IDL.Vec(NfcDetectionLog)], ['query']),
  'getNfcPermission' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(NfcPermission)],
      ['query'],
    ),
  'getNfcSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(NfcSettings)],
      ['query'],
    ),
  'getNfcTransactions' : IDL.Func([], [IDL.Vec(NfcTransaction)], ['query']),
  'getPaymentTransactions' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'getPdfGuide' : IDL.Func([IDL.Text], [IDL.Opt(PdfGuide)], ['query']),
  'getPortfolioProjects' : IDL.Func([], [IDL.Vec(PortfolioProject)], ['query']),
  'getReinforcementProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ReinforcementProgress)],
      ['query'],
    ),
  'getSecurityAuditLogById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SecurityAuditLog)],
      ['query'],
    ),
  'getSecurityAuditLogs' : IDL.Func([], [IDL.Vec(SecurityAuditLog)], ['query']),
  'getSecurityAuditLogsByEncryptionStatus' : IDL.Func(
      [EncryptionStatus],
      [IDL.Vec(SecurityAuditLog)],
      ['query'],
    ),
  'getSecurityAuditLogsByTransactionId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SecurityAuditLog)],
      ['query'],
    ),
  'getSecurityAuditLogsByTransactionStatus' : IDL.Func(
      [NfcTransactionStatus],
      [IDL.Vec(SecurityAuditLog)],
      ['query'],
    ),
  'getSecurityAuditLogsByTransferType' : IDL.Func(
      [NfcTransferType],
      [IDL.Vec(SecurityAuditLog)],
      ['query'],
    ),
  'getSecurityAuditSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'verifiedCount' : IDL.Nat,
          'failedCount' : IDL.Nat,
          'phoneToPhoneCount' : IDL.Nat,
          'totalLogs' : IDL.Nat,
          'completedCount' : IDL.Nat,
          'cardToPhoneCount' : IDL.Nat,
          'failedTransactionCount' : IDL.Nat,
          'unverifiedCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSecurityVerificationResult' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SecurityVerificationResult)],
      ['query'],
    ),
  'getSecurityVerificationResultsByStatus' : IDL.Func(
      [EncryptionStatus],
      [IDL.Vec(SecurityVerificationResult)],
      ['query'],
    ),
  'getSecurityVerificationResultsByTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(SecurityVerificationResult)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionReceipt' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TransactionReceipt)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletBalance' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WalletBalance)],
      ['query'],
    ),
  'getWidgetConfig' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WidgetConfig)],
      ['query'],
    ),
  'getWidgetData' : IDL.Func([IDL.Principal], [IDL.Opt(WidgetData)], ['query']),
  'incrementVisitCount' : IDL.Func([], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeDefaultPdfGuide' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCardToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'recordChildActivityStats' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Int],
      [],
      [],
    ),
  'recordFilterStatus' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
  'recordNfcAlert' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordNfcComplianceReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'recordNfcDetectionLog' : IDL.Func(
      [NfcTransferType, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'recordNfcTransaction' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        NfcTransferType,
        NfcTransactionStatus,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'recordPaymentTransaction' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'recordReinforcementProgress' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'recordSecurityAuditLog' : IDL.Func(
      [
        IDL.Text,
        NfcTransactionStatus,
        EncryptionStatus,
        NfcTransferType,
        IDL.Principal,
        IDL.Principal,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'recordSecurityVerificationResult' : IDL.Func(
      [IDL.Text, EncryptionStatus, IDL.Text],
      [],
      [],
    ),
  'recordTransactionReceipt' : IDL.Func(
      [
        IDL.Text,
        IDL.Principal,
        IDL.Nat,
        IDL.Text,
        NfcTransactionStatus,
        NfcTransferType,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'recordWidgetConfig' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerNfcPermission' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
  'updateCallerNfcSettings' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCurrencyConversionRate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateHomeContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateNfcPermission' : IDL.Func([IDL.Principal, IDL.Bool, IDL.Bool], [], []),
  'updateNfcSettings' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updatePdfGuide' : IDL.Func(
      [IDL.Text, IDL.Vec(PdfSection), IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updatePortfolioProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'uploadAdminApkFile' : IDL.Func([ExternalBlob, IDL.Text], [], []),
  'validateWidgetAuthToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PdfSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const AdminApkFile = IDL.Record({
    'uploadTimestamp' : IDL.Int,
    'version' : IDL.Text,
    'fileRef' : ExternalBlob,
  });
  const PdfGuide = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'navigation' : IDL.Vec(IDL.Text),
    'sections' : IDL.Vec(PdfSection),
    'branding' : IDL.Text,
  });
  const EncryptionStatus = IDL.Variant({
    'verified' : IDL.Null,
    'unverified' : IDL.Null,
    'failed' : IDL.Null,
  });
  const SecurityVerificationResult = IDL.Record({
    'verificationDetails' : IDL.Text,
    'timestamp' : IDL.Int,
    'encryptionStatus' : EncryptionStatus,
    'transactionId' : IDL.Text,
  });
  const NfcPermission = IDL.Record({
    'phoneTransferConsent' : IDL.Bool,
    'user' : IDL.Principal,
    'lastUpdated' : IDL.Int,
    'cardScanConsent' : IDL.Bool,
  });
  const NfcSettings = IDL.Record({
    'cardScanEnabled' : IDL.Bool,
    'transactionLimit' : IDL.Nat,
    'user' : IDL.Principal,
    'lastUpdated' : IDL.Int,
    'phoneTransferEnabled' : IDL.Bool,
    'defaultCurrency' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WalletBalance = IDL.Record({
    'balance' : IDL.Nat,
    'user' : IDL.Principal,
    'lastUpdated' : IDL.Int,
    'currency' : IDL.Text,
  });
  const FilterStatus = IDL.Record({
    'lastUpdated' : IDL.Int,
    'isActive' : IDL.Bool,
    'level' : IDL.Text,
  });
  const ChildActivityStats = IDL.Record({
    'blockedAttempts' : IDL.Nat,
    'lastActivity' : IDL.Int,
    'totalTimeOnline' : IDL.Nat,
    'childId' : IDL.Principal,
    'safeSearchEnabled' : IDL.Bool,
    'parentId' : IDL.Principal,
  });
  const AlertType = IDL.Variant({
    'violence' : IDL.Null,
    'inappropriateLanguage' : IDL.Null,
    'generalSafety' : IDL.Null,
    'explicitContent' : IDL.Null,
  });
  const AlertCategory = IDL.Variant({
    'warning' : IDL.Null,
    'educational' : IDL.Null,
    'contentBlock' : IDL.Null,
  });
  const AlertMessageV2 = IDL.Record({
    'id' : IDL.Text,
    'alertType' : AlertType,
    'title' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : AlertCategory,
    'priority' : IDL.Nat,
  });
  const ReinforcementProgress = IDL.Record({
    'positiveActions' : IDL.Nat,
    'childId' : IDL.Principal,
    'parentId' : IDL.Principal,
    'milestonesAchieved' : IDL.Nat,
    'lastReward' : IDL.Int,
  });
  const WidgetData = IDL.Record({
    'filterStatus' : FilterStatus,
    'childStats' : IDL.Vec(ChildActivityStats),
    'lastAlert' : IDL.Opt(AlertMessageV2),
    'reinforcementProgress' : IDL.Vec(ReinforcementProgress),
    'timestamp' : IDL.Int,
    'parentId' : IDL.Principal,
  });
  const CardToken = IDL.Record({
    'token' : IDL.Text,
    'cardType' : IDL.Text,
    'createdAt' : IDL.Int,
    'last4' : IDL.Text,
    'issuer' : IDL.Text,
    'expiry' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CurrencyConversionRate = IDL.Record({
    'toCurrency' : IDL.Text,
    'fromCurrency' : IDL.Text,
    'rate' : IDL.Nat,
    'lastUpdated' : IDL.Int,
  });
  const HomeContent = IDL.Record({
    'missionStatement' : IDL.Text,
    'heroText' : IDL.Text,
  });
  const NfcAlert = IDL.Record({
    'id' : IDL.Text,
    'alertType' : IDL.Text,
    'user' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const NfcComplianceReport = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'reportType' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const NfcTransferType = IDL.Variant({
    'phoneToPhone' : IDL.Null,
    'cardToPhone' : IDL.Null,
  });
  const NfcDetectionLog = IDL.Record({
    'id' : IDL.Text,
    'detectedType' : NfcTransferType,
    'status' : IDL.Text,
    'user' : IDL.Principal,
    'cardToken' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const NfcTransactionStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const NfcTransaction = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'status' : NfcTransactionStatus,
    'transferType' : NfcTransferType,
    'from' : IDL.Principal,
    'description' : IDL.Text,
    'cardToken' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const PaymentTransaction = IDL.Record({
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const PortfolioProject = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imageRefs' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'details' : IDL.Text,
  });
  const SecurityAuditLog = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'status' : NfcTransactionStatus,
    'transferType' : NfcTransferType,
    'from' : IDL.Principal,
    'description' : IDL.Text,
    'verificationDetails' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'encryptionStatus' : EncryptionStatus,
    'transactionId' : IDL.Text,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TransactionReceipt = IDL.Record({
    'to' : IDL.Principal,
    'status' : NfcTransactionStatus,
    'transferType' : NfcTransferType,
    'from' : IDL.Principal,
    'description' : IDL.Text,
    'cardToken' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const WidgetConfig = IDL.Record({
    'theme' : IDL.Text,
    'refreshInterval' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'widgetSize' : IDL.Text,
    'parentId' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPortfolioProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPdfGuide' : IDL.Func(
        [IDL.Text, IDL.Vec(PdfSection), IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteAdminApkFile' : IDL.Func([], [], []),
    'deletePdfGuide' : IDL.Func([IDL.Text], [], []),
    'deletePortfolioProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateWidgetAuthToken' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getAdminApkFile' : IDL.Func([], [IDL.Opt(AdminApkFile)], ['query']),
    'getAllPdfGuides' : IDL.Func([], [IDL.Vec(PdfGuide)], ['query']),
    'getAllSecurityVerificationResults' : IDL.Func(
        [],
        [IDL.Vec(SecurityVerificationResult)],
        ['query'],
      ),
    'getCallerNfcPermission' : IDL.Func(
        [],
        [IDL.Opt(NfcPermission)],
        ['query'],
      ),
    'getCallerNfcSettings' : IDL.Func([], [IDL.Opt(NfcSettings)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWalletBalance' : IDL.Func(
        [],
        [IDL.Opt(WalletBalance)],
        ['query'],
      ),
    'getCallerWidgetData' : IDL.Func([], [IDL.Opt(WidgetData)], ['query']),
    'getCardToken' : IDL.Func([IDL.Text], [IDL.Opt(CardToken)], ['query']),
    'getChildActivityStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ChildActivityStats)],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCurrencyConversionRate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CurrencyConversionRate)],
        ['query'],
      ),
    'getFilterStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FilterStatus)],
        ['query'],
      ),
    'getHomeContent' : IDL.Func([], [IDL.Opt(HomeContent)], ['query']),
    'getNfcAlerts' : IDL.Func([], [IDL.Vec(NfcAlert)], ['query']),
    'getNfcComplianceReports' : IDL.Func(
        [],
        [IDL.Vec(NfcComplianceReport)],
        ['query'],
      ),
    'getNfcDetectionLogs' : IDL.Func([], [IDL.Vec(NfcDetectionLog)], ['query']),
    'getNfcPermission' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NfcPermission)],
        ['query'],
      ),
    'getNfcSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NfcSettings)],
        ['query'],
      ),
    'getNfcTransactions' : IDL.Func([], [IDL.Vec(NfcTransaction)], ['query']),
    'getPaymentTransactions' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getPdfGuide' : IDL.Func([IDL.Text], [IDL.Opt(PdfGuide)], ['query']),
    'getPortfolioProjects' : IDL.Func(
        [],
        [IDL.Vec(PortfolioProject)],
        ['query'],
      ),
    'getReinforcementProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ReinforcementProgress)],
        ['query'],
      ),
    'getSecurityAuditLogById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditLogs' : IDL.Func(
        [],
        [IDL.Vec(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditLogsByEncryptionStatus' : IDL.Func(
        [EncryptionStatus],
        [IDL.Vec(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditLogsByTransactionId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditLogsByTransactionStatus' : IDL.Func(
        [NfcTransactionStatus],
        [IDL.Vec(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditLogsByTransferType' : IDL.Func(
        [NfcTransferType],
        [IDL.Vec(SecurityAuditLog)],
        ['query'],
      ),
    'getSecurityAuditSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'verifiedCount' : IDL.Nat,
            'failedCount' : IDL.Nat,
            'phoneToPhoneCount' : IDL.Nat,
            'totalLogs' : IDL.Nat,
            'completedCount' : IDL.Nat,
            'cardToPhoneCount' : IDL.Nat,
            'failedTransactionCount' : IDL.Nat,
            'unverifiedCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSecurityVerificationResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SecurityVerificationResult)],
        ['query'],
      ),
    'getSecurityVerificationResultsByStatus' : IDL.Func(
        [EncryptionStatus],
        [IDL.Vec(SecurityVerificationResult)],
        ['query'],
      ),
    'getSecurityVerificationResultsByTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(SecurityVerificationResult)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionReceipt' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TransactionReceipt)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletBalance' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WalletBalance)],
        ['query'],
      ),
    'getWidgetConfig' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WidgetConfig)],
        ['query'],
      ),
    'getWidgetData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WidgetData)],
        ['query'],
      ),
    'incrementVisitCount' : IDL.Func([], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeDefaultPdfGuide' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCardToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'recordChildActivityStats' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Int],
        [],
        [],
      ),
    'recordFilterStatus' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'recordNfcAlert' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordNfcComplianceReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'recordNfcDetectionLog' : IDL.Func(
        [NfcTransferType, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'recordNfcTransaction' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          NfcTransferType,
          NfcTransactionStatus,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'recordPaymentTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'recordReinforcementProgress' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'recordSecurityAuditLog' : IDL.Func(
        [
          IDL.Text,
          NfcTransactionStatus,
          EncryptionStatus,
          NfcTransferType,
          IDL.Principal,
          IDL.Principal,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'recordSecurityVerificationResult' : IDL.Func(
        [IDL.Text, EncryptionStatus, IDL.Text],
        [],
        [],
      ),
    'recordTransactionReceipt' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Nat,
          IDL.Text,
          NfcTransactionStatus,
          NfcTransferType,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'recordWidgetConfig' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerNfcPermission' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
    'updateCallerNfcSettings' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCurrencyConversionRate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateHomeContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateNfcPermission' : IDL.Func(
        [IDL.Principal, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updateNfcSettings' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updatePdfGuide' : IDL.Func(
        [IDL.Text, IDL.Vec(PdfSection), IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updatePortfolioProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateWalletBalance' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'uploadAdminApkFile' : IDL.Func([ExternalBlob, IDL.Text], [], []),
    'validateWidgetAuthToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };